#/bin/bash
cd pictures/light-mode/symmetric-difference/associativity/
lualatex A.tex
lualatex A_sdiff_B.tex
lualatex A_sdiff_B_sdiff_C.tex
lualatex B_sdiff_C.tex
lualatex C.tex
cd ../via-unions-and-intersections/
lualatex Venn0001.tex
lualatex Venn0110.tex
lualatex Venn0111.tex
cd ../../../../
cd pictures/dark-mode/symmetric-difference/associativity/
lualatex A.tex
lualatex A_sdiff_B.tex
lualatex A_sdiff_B_sdiff_C.tex
lualatex B_sdiff_C.tex
lualatex C.tex
cd ../via-unions-and-intersections/
lualatex Venn0001.tex
lualatex Venn0110.tex
lualatex Venn0111.tex
